# Generated by Django 2.2.7 on 2019-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Statename', models.CharField(max_length=150)),
                ('Districtname', models.EmailField(blank=True, max_length=254)),
                ('Cropyear', models.CharField(max_length=50)),
                ('Season', models.CharField(max_length=150)),
                ('Crop', models.CharField(max_length=150)),
                ('Area', models.CharField(max_length=150)),
                ('Production', models.CharField(max_length=150)),
                ('cropprod', models.TextField()),
            ],
        ),
    ]
